-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\natha\Documents\projects\brain_hack\neuro-rtl\codegen\eeg_inverse_hls_float\hdlsrc\eeg_inverse_hls_float_fixpt.vhd
-- Created: 2026-01-30 10:42:15
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: eeg_inverse_hls_float_fixpt
-- Source Path: eeg_inverse_hls_float_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.eeg_inverse_hls_float_fixpt_pkg.ALL;

ENTITY eeg_inverse_hls_float_fixpt IS
  PORT( Y_block                           :   IN    vector_of_std_logic_vector64(0 TO 28);  -- sfix64_En40 [29]
        K                                 :   IN    matrix_of_std_logic_vector64(0 TO 899, 0 TO 28);  -- sfix64_En40 [900x29]
        J_block                           :   OUT   vector_of_std_logic_vector64(0 TO 899)  -- sfix64_En40 [900]
        );
END eeg_inverse_hls_float_fixpt;


ARCHITECTURE rtl OF eeg_inverse_hls_float_fixpt IS

  -- Signals
  SIGNAL K_signed                         : matrix_of_signed64(0 TO 899, 0 TO 28);  -- sfix64_En40 [900x29]
  SIGNAL Y_block_signed                   : vector_of_signed64(0 TO 28);  -- sfix64_En40 [29]
  SIGNAL J_block_tmp                      : vector_of_signed64(0 TO 899);  -- sfix64_En40 [900]

BEGIN
  outputgen2: FOR k1 IN 0 TO 899 GENERATE
    outputgen3: FOR k2 IN 0 TO 28 GENERATE
      K_signed(k1, k2) <= signed(K(k1, k2));
    END GENERATE;
  END GENERATE;

  outputgen1: FOR k1 IN 0 TO 28 GENERATE
    Y_block_signed(k1) <= signed(Y_block(k1));
  END GENERATE;

  -- 'eeg_inverse_hls_float_fixpt:30' J_block(s,b) = acc;
  -- 'eeg_inverse_hls_float_fixpt:28' acc(:) = acc + K(s,c) * Y_block(c,b);
  -- #pragma HLS UNROLL factor=8
  -- 'eeg_inverse_hls_float_fixpt:26' for c = fi(1, 1, 2, 0, fm):N_elec
  -- 'eeg_inverse_hls_float_fixpt:25' acc = fi(0, 1, 15, 0, fm);
  -- #pragma HLS PIPELINE
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --                                                                          %
  --          Generated by MATLAB 25.2 and Fixed-Point Designer 25.2          %
  --                                                                          %
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  -- Y_block: [64 x block_size]
  -- K:       [Ns x 64]
  -- J_block: [Ns x block_size]
  -- 'eeg_inverse_hls_float_fixpt:13' fm = get_fimath();
  -- 'eeg_inverse_hls_float_fixpt:15' Ns = fi(900, 1, 11, 0, fm);
  -- 'eeg_inverse_hls_float_fixpt:16' B  = fi(1, 1, 2, 0, fm);
  -- 'eeg_inverse_hls_float_fixpt:17' N_elec = fi(29, 1, 6, 0, fm);
  -- 'eeg_inverse_hls_float_fixpt:19' J_block = fi(zeros(fi_toint(Ns), fi_toint(B)), 1, 64, 40, fm);
  -- 'eeg_inverse_hls_float_fixpt:21' for b = fi(1, 1, 2, 0, fm):B
  -- #pragma HLS PIPELINE
  -- 'eeg_inverse_hls_float_fixpt:23' for s = fi(1, 1, 2, 0, fm):Ns
  p1_output : PROCESS (K_signed, Y_block_signed)
    VARIABLE J_block1 : vector_of_signed64(0 TO 899);
    VARIABLE s_0 : signed(10 DOWNTO 0);
    VARIABLE acc : signed(14 DOWNTO 0);
    VARIABLE c_0 : signed(5 DOWNTO 0);
    VARIABLE add_temp : signed(31 DOWNTO 0);
    VARIABLE add_temp_0 : signed(31 DOWNTO 0);
    VARIABLE add_cast : signed(128 DOWNTO 0);
    VARIABLE mul_temp : signed(127 DOWNTO 0);
    VARIABLE add_cast_0 : signed(128 DOWNTO 0);
    VARIABLE add_temp_1 : signed(128 DOWNTO 0);
  BEGIN
    acc := to_signed(16#0000#, 15);
    add_temp := to_signed(16#00000000#, 32);
    add_temp_0 := to_signed(16#00000000#, 32);
    mul_temp := to_signed(0, 128);
    add_temp_1 := to_signed(0, 129);
    s_0 := to_signed(16#000#, 11);
    c_0 := to_signed(16#00#, 6);
    add_cast := to_signed(0, 129);
    add_cast_0 := to_signed(0, 129);
    J_block1 := (OTHERS => to_signed(0, 64));

    FOR s IN 0 TO 899 LOOP
      add_temp := to_signed(s + 1, 32);
      s_0 := add_temp(10 DOWNTO 0);
      acc := to_signed(16#0000#, 15);

      FOR c IN 0 TO 28 LOOP
        add_temp_0 := to_signed(c + 1, 32);
        c_0 := add_temp_0(5 DOWNTO 0);
        add_cast := resize(acc & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 129);
        mul_temp := K_signed(to_integer(resize(s_0, 32) - 1), to_integer(resize(c_0, 32) - 1)) * Y_block_signed(to_integer(resize(c_0, 32) - 1));
        add_cast_0 := resize(mul_temp, 129);
        add_temp_1 := add_cast + add_cast_0;
        IF ((add_temp_1(128) = '0') AND (add_temp_1(127 DOWNTO 94) /= "0000000000000000000000000000000000")) OR ((add_temp_1(128) = '0') AND (add_temp_1(94 DOWNTO 80) = "011111111111111")) THEN 
          acc := "011111111111111";
        ELSIF (add_temp_1(128) = '1') AND (add_temp_1(127 DOWNTO 94) /= "1111111111111111111111111111111111") THEN 
          acc := "100000000000000";
        ELSE 
          acc := add_temp_1(94 DOWNTO 80) + ('0' & add_temp_1(79));
        END IF;
      END LOOP;

      J_block1(to_integer(resize(s_0, 32) - 1)) := resize(acc & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
    END LOOP;

    J_block_tmp <= J_block1;
  END PROCESS p1_output;


  outputgen: FOR k1 IN 0 TO 899 GENERATE
    J_block(k1) <= std_logic_vector(J_block_tmp(k1));
  END GENERATE;

END rtl;

